version: '3.8'

networks:
  web:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - ./backend/uploads:/uploads
    depends_on:
      - backend
      - frontend
    networks:
      - web

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    hostname: backend
    ports:
      - "3001:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - mongo
    networks:
      - web
    command: >
      sh -c "
        npm install &&
        chmod -R 777 /app/uploads &&
        ls -la /app/uploads &&
        echo 'Creating admin user...' &&
        node admin-setup.js &&
        echo 'Starting backend server...' &&
        node server.js
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    hostname: frontend
    ports:
      - "3000:80"
    networks:
      - web

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - web
    ports:
      - "27017:27017"

  init-admin:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: init-admin
    environment:
      - MONGODB_URI=mongodb://mongo:27017/hackathon
      - ADMIN_PASSWORD=admin123
    volumes:
      - ./backend:/app
    working_dir: /app
    depends_on:
      - mongo
    networks:
      - web
    command: >
      sh -c "
        npm install &&
        echo 'Creating admin user...' &&
        node admin-setup.js
      "
    restart: "no"

volumes:
  mongo-data: